config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root "events#index"

  resources :events
  resources :users, only: [:show, :edit, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  # Событие принадлежит юзеру
  belongs_to :user

  # Валидируем юзера на присутствие. В Rails 5 связи
  # валидируются по умолчанию
  validates :user, presence: true

  # Валидируем заголовок, он не может быть длиннее 255 букв
  validates :title, presence: true, length: {maximum: 255}
  # У события должны быть заполнены место и время
  validates :address, presence: true
  validates :datetime, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  #devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  # Юзер может создавать много событий
  has_many :events

  # Добавим заодно валидации для юзера
  # Имя не не более 35 символов
  validates :name, presence: true, length: {maximum: 35}

  before_validation :set_name, on: :create

  private

  def set_name
    self.name = "Товарисч №#{rand(777)}" if self.name.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # Настройка для работы девайза при правке профиля юзера
  before_action :configure_permitted_parameters, if: :devise_controller?

  # Хелпер метод, доступный во вьюхах
  helper_method :current_user_can_edit?

  # Настройка для девайза — разрешаем обновлять профиль, но обрезаем
  # параметры, связанные со сменой пароля.
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(
      :account_update,
      keys: [:password, :password_confirmation, :current_password]
    )
  end

  # Вспомогательный метод, возвращает true, если текущий залогиненный юзер
  # может править указанное событие
  def current_user_can_edit?(event)
    user_signed_in? && event.user == current_user
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # Задаем объект @event для тех действий, где он нужен
  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_event, only: [:show]
  before_action :set_current_user_event, only: [:edit, :update, :destroy]

  def index
    @events = Event.all
  end

  def show
  end

  def new
    @event = current_user.events.build
  end

  def edit
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      redirect_to @event, notice: 'Event was successfully created.'
    else
      render :new
    end
  end

  def update
    if @event.update(event_params)
      redirect_to @event, notice: 'Event was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to events_url, notice: 'Event was successfully destroyed.'
  end

  private

  def set_current_user_event
    @event = current_user.events.find(params[:id])
  end

  def set_event
    @event = Event.find(params[:id])
  end

  # редактируем параметры события
  def event_params
    params.require(:event).permit(:title, :address, :datetime, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_current_user, except: [:show]

  def show
    @user = User.find(params[:id])
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  private

  def set_current_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_avatar(user)
    asset_path('user.png')
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event.html.erb
<div class="col col-sm-6 col-md-4 p-3">
  <div class="card thumbnail">

    <%= content_tag 'div', '', class: 'event-background',
                    style: "background-image: url(#{asset_path('bb.jpg')})" %>

    <div class="thumbnail-inner event-info-inner">
      <div class="card-body">
        <div class="event-description">
          <div class="card-title">
            <h3 class="text-wrap"><%= link_to event.title, event_path(event) %></h3>
          </div>
          <div class="card-text">
            <h4><small><%= l event.datetime, format: :short %></small></h4>
            <div class="buffer-both"><%= event.address %></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <%= render partial: 'partials/form_errors', locals: {model: @event} %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :datetime %>
    <p><%= f.datetime_select :datetime, class: 'form-control' %></p>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="actions mt-3">
    <%= f.submit 'Сохранить', class: 'btn btn-primary' %>
    или <%= link_to 'вернуться', :back %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h2 class="mt-3">События</h2>

<div class="buffer-both">
  <%= link_to 'Создать событие', new_event_path, class: 'btn btn-success btn-sm mt-3' %>
</div>

<div class="row buffer-bottom mt-3">
  <%= render partial: 'events/event', collection: @events %>
</div>

app/views/events/new.html.erb
<h1>Новое событие</h1>

<div class="row">
  <div class="col-md-6 buffer-top">
    <%= render 'form' %>
  </div>
</div>

app/views/events/show.html.erb
<div class="event">
  <div class="event-info row">
    <div class="col-md-12">
      <%= content_tag 'div', '', class: 'event-background',
        style: "background-image: url(#{asset_path('bb.jpg')})" %>

      <div class="event-info-inner row">
        <div class="col-md-6">
          <div class="event-description">
            <h1><%= @event.title %></h1>
            <h3><%= @event.datetime %></h3>
            <h3><small><%= link_to @event.address,
                "https://yandex.ru/maps/?text=#{@event.address}" %></small></h3>
            <p><%= @event.description %></p>
          </div>

          <%# if current_user_can_edit?(@event) %>
            <div class="buffer-both">
              <%#= link_to 'Изменить', edit_event_path(@event),
                class: 'btn btn-primary' %>
             </div>
          <%# end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Barbq</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
        <a><%= link_to 'BBQ', root_path, class: 'navbar-brand' %></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <% if user_signed_in? %>
          <%= link_to 'Профиль', current_user, class: 'nav-link' %>
          <%= button_to 'Выйти', destroy_user_session_path, method: :delete, class: 'nav-link border-0 bg-transparent' %>
        <% else %>
          <%= link_to 'Войти', new_user_session_path, class: 'nav-link'  %>
          <%= link_to 'Зарегистрироваться', new_user_registration_path, class: 'nav-link'  %>
        <% end %>
      </div>
    </div>
  </div>
</nav>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= yield %>
        </div>
        <div class="col-lg-3">
        </div><!--/span-->
      </div><!--/row-->
    </div> <!-- /container -->
  </body>
</html>

app/views/partials/_form_errors.html.erb
<% errors = model.errors %>

<% if errors.any? %>
  <div class="alert alert-danger">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <div class="lead buffer-bottom">
      Errors <%#= errors.count %>
    </div>

    <ul>
      <% errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>

  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user, html: {multipart: true} do |f| %>
  <%= render partial: 'partials/form_errors', locals: {model: @user} %>

  <div class="form-group mt-3">
    <%= f.label 'Имя' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group mt-3">
    <%= f.label 'Email' %>
    <%= f.text_field :email, class: 'form-control ' %>
  </div>

  <div class="actions">
    <%= f.submit 'Сохранить', class: 'btn btn-primary mt-3' %>
    или <%= link_to 'вернуться', :back, class: 'pt-3' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="w-100 d-flex flex-column justify-content-center align-items-right">
  <div class="col-md-6 col-12 ">
    <h3 class="mt-5"><%= 'Редактирование профиля' %></h3>

    <%= render "form", user: @user %>

  </div>
</div>

app/views/users/show.html.erb
<div class="text-center">
  <h1><%= @user.name %></h1>
  <%= image_tag user_avatar(@user) %>
  <% if @user == current_user %>
    <p class="buffer-top"><%= link_to 'Редактировать профиль', edit_user_path(@user), class: 'btn btn-default' %></p>
  <% end %>
</div>

<div class="row">
  <div class="col-md-12">
    <% if @user.events.any? %>
      <h3>Организовал:</h3>
      <div class="row">
        <%= render partial: 'events/event', collection: @user.events %>
      </div>
    <% else %>
      <p class="buffer-top">Пользователь пока не организовал ни одного события</p>
    <% end %>
  </div>
</div>